export const window: string;
export const hidden: string;
export const maximized: string;
export const body: string;
export const head: string;
export const headIcons: string;
export const iconMaximize: string;
export const iconMinimize: string;
export const iconClose: string;
